---
- name: Create a database for Sonar.
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_db:
    name: "{{ sonar_database_name }}"
    encoding: SQL_ASCII
    state: present

- name: Create a sonar user.
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_user:
    name: "{{ sonar_database_username }}"
    password: "{{ sonar_database_password }}"
    db: "{{ sonar_database_name }}"
    priv: "ALL"

- name: Configure SonarQube JDBC settings for Postgres.
  lineinfile:
    dest: /usr/local/sonar/conf/sonar.properties
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: restart sonar
  with_items:
    - regexp: "^sonar.jdbc.username"
      line: "sonar.jdbc.username={{ sonar_database_username }}"
    - regexp: "^sonar.jdbc.password"
      line: "sonar.jdbc.password={{ sonar_database_password }}"
    - regexp: "^sonar.jdbc.url"
      line: "sonar.jdbc.url=jdbc:postgresql://{{ sonar_database_host }}:{{ sonar_database_port }}/{{ sonar_database_name }}"
    - regexp: "^sonar.web.context"
      line: "sonar.web.context={{ sonar_web_context }}"